<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://securitybugtracker/V1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://securitybugtracker/V1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soapbind="http://schemas.xmlsoap.org/wsdl/soap/">

	<wsdl:types>
		<xsd:schema targetNamespace="http://securitybugtracker" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://securitybugtracker/V1" schemaLocation="http://localhost/security-bugtracker/webissues-server-1.1.4/client/security_tools/openvas/openvas.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="run_openvas_input">
		<wsdl:part name="run_openvas" element="tns:run_openvas"/>
	</wsdl:message>
	<wsdl:message name="run_openvas_output">
		<wsdl:part name="run_openvas_Response" element="tns:run_openvas_Response"/>
	</wsdl:message>

	<wsdl:portType name="ws_securitybugtracker_PortType">
		<wsdl:operation name="run_openvas">
			<wsdl:documentation>WebService for run_openvas
			</wsdl:documentation>
			<wsdl:input message="tns:run_openvas_input"/>
			<wsdl:output message="tns:run_openvas_output"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="ws_securitybugtracker_Binding" type="tns:ws_securitybugtracker_PortType">
		<soapbind:binding transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="run_openvas">
			<soapbind:operation soapAction="run_openvas" style="document"/>
			<wsdl:input>
				<soapbind:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soapbind:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="ws_securitybugtracker">
		<wsdl:port name="ws_securitybugtrackerPort" binding="tns:ws_securitybugtracker_Binding">
			<soapbind:address location="http://localhost/security-bugtracker/webissues-server-1.1.4/client/security_tools/openvas/openvas.php"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
