<?php

$CONF_SERVER_IPS_EXPLODE = ",";
$CONF_ISSUE_DEFAULT_CVENAME = "nocve";
$CONF_ISSUE_DEFAULT_CWENAME = "nocwe";
$CONF_OPENVAS_WS_LOGIN = "test";
$CONF_OPENVAS_WS_PASSWORD = "test";
$CONF_OPENVAS_WS_ENDPOINT = "http://localhost:81/webissues-server-2.0.0/client/security_tools/openvas/openvas.php";
$CONF_ID_ATTRIBUTE_FOLDER_WEB_URL = 115;
$CONF_ID_ATTRIBUTE_FOLDER_CODES_PATH = 114;
$CONF_ID_ATTRIBUTE_FOLDER_SERVERS_USE = 113;
$CONF_ID_ATTRIBUTE_FOLDER_SERVERS_IPSADDRESS = 112;
$CONF_ID_ATTRIBUTE_FOLDER_SCANS_TOOL = 116;
$CONF_ID_ATTRIBUTE_FOLDER_SCANS_TIME = 117;
$CONF_ID_ATTRIBUTE_FOLDER_SCANS_SEVERITY = 118;
$CONF_ID_ATTRIBUTE_FOLDER_SCANS_TARGETID = 119;
$CONF_ID_ATTRIBUTE_FOLDER_SCANS_TASKID = 120;
$CONF_ID_ATTRIBUTE_FOLDER_SCANS_REPORTID = 121;
$CONF_ID_ATTRIBUTE_FOLDER_SCANS_ALERTID = 122;
$CONF_ID_ATTRIBUTE_FOLDER_BUGS_TARGET = 109;
$CONF_ID_ATTRIBUTE_FOLDER_BUGS_CVE = 110;
$CONF_ID_ATTRIBUTE_FOLDER_BUGS_CWE = 111;
$CONF_ID_TYPE_FOLDER_BUGS = 2;
$CONF_ID_TYPE_FOLDER_SERVERS = 32;
$CONF_ID_TYPE_FOLDER_CODES = 33;
$CONF_ID_TYPE_FOLDER_WEB = 35;
$CONF_ID_TYPE_FOLDER_SCANS = 34;
