<?php

$CONF_SERVER_IPS_EXPLODE = ",";
$CONF_ISSUE_DEFAULT_CVENAME = "nocve";
$CONF_ISSUE_DEFAULT_CWENAME = "nocwe";
$CONF_OPENVAS_WS_LOGIN = "test";
$CONF_OPENVAS_WS_PASSWORD = "test";
$CONF_OPENVAS_WS_ENDPOINT = "http://localhost/security-bugtracker/webissues-server-1.1.4/client/security_tools/openvas/openvas.php";
$CONF_ID_ATTRIBUTE_FOLDER_WEB_URL = 45;
$CONF_ID_ATTRIBUTE_FOLDER_CODES_PATH = 44;
$CONF_ID_ATTRIBUTE_FOLDER_SERVERS_USE = 43;
$CONF_ID_ATTRIBUTE_FOLDER_SERVERS_IPSADDRESS = 42;
$CONF_ID_ATTRIBUTE_FOLDER_SCANS_TOOL = 46;
$CONF_ID_ATTRIBUTE_FOLDER_SCANS_TIME = 47;
$CONF_ID_ATTRIBUTE_FOLDER_SCANS_SEVERITY = 48;
$CONF_ID_ATTRIBUTE_FOLDER_SCANS_TARGETID = 49;
$CONF_ID_ATTRIBUTE_FOLDER_SCANS_TASKID = 50;
$CONF_ID_ATTRIBUTE_FOLDER_SCANS_REPORTID = 51;
$CONF_ID_ATTRIBUTE_FOLDER_SCANS_ALERTID = 52;
$CONF_ID_ATTRIBUTE_FOLDER_BUGS_TARGET = 39;
$CONF_ID_ATTRIBUTE_FOLDER_BUGS_CVE = 40;
$CONF_ID_ATTRIBUTE_FOLDER_BUGS_CWE = 41;
$CONF_ID_TYPE_FOLDER_BUGS = 2;
$CONF_ID_TYPE_FOLDER_SERVERS = 12;
$CONF_ID_TYPE_FOLDER_CODES = 13;
$CONF_ID_TYPE_FOLDER_WEB = 15;
$CONF_ID_TYPE_FOLDER_SCANS = 14;

?>
